/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships.index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/scholarships/$slug',
  path: '/scholarships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/courses/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/courses/'
    | '/jobs/'
    | '/scholarships/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/courses/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/courses'
    | '/jobs'
    | '/scholarships'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/courses/$slug'
    | '/jobs/$slug'
    | '/scholarships/$slug'
    | '/courses/'
    | '/jobs/'
    | '/scholarships/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/scholarships/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
